project:
  type: website
  output-dir: ../docs

website:
  description: "A blog about statistical methods and boxing"
  site-url: https://thsis.github.io/xKO/
  title: "Expected Knockout"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/thsis
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css



